//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSokoban {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resourcen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourcen() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcSokoban.Resourcen", typeof(Resourcen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap borgar {
            get {
                object obj = ResourceManager.GetObject("borgar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Character4 {
            get {
                object obj = ResourceManager.GetObject("Character4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crate_Brown {
            get {
                object obj = ResourceManager.GetObject("Crate_Brown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EndPoint_Red {
            get {
                object obj = ResourceManager.GetObject("EndPoint_Red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EndPointCharacter {
            get {
                object obj = ResourceManager.GetObject("EndPointCharacter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EndPointCrate_Brown {
            get {
                object obj = ResourceManager.GetObject("EndPointCrate_Brown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GroundGravel_Grass {
            get {
                object obj = ResourceManager.GetObject("GroundGravel_Grass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####
        /// #   ####
        /// #   #  #
        /// ##    .#
        ///### ###.#
        ///# $ # #.#
        ///# $$# ###
        ///#@  #
        ///#####
        ///.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####
        /// #   ####
        /// #   #  #
        /// ##    .#
        ///### ###.#
        ///# $ # #.#
        ///# $$# ###
        ///#@  #
        ///#####
        ///.
        /// </summary>
        internal static string level11 {
            get {
                return ResourceManager.GetString("level11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   #######
        ///  #     #
        ///  # $ @ #
        ///##### # #
        ///# $     #
        ///#  #$## ##
        ///#..$  #  #
        ///#..      #
        ///##########.
        /// </summary>
        internal static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   #######
        ///  #     #
        ///  # $ @ #
        ///##### # #
        ///# $     #
        ///#  #$## ##
        ///#..$  #  #
        ///#..      #
        ///##########.
        /// </summary>
        internal static string level21 {
            get {
                return ResourceManager.GetString("level21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   ######
        ///  #..*.#
        ///  #.$  #
        ///  ## $ #
        ///  ##$ ##
        ///  #@$ #
        ///  ##  #
        ///   ####.
        /// </summary>
        internal static string level3 {
            get {
                return ResourceManager.GetString("level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   ######
        ///  #..*.#
        ///  #.$  #
        ///  ## $ #
        ///  ##$ ##
        ///  #@$ #
        ///  ##  #
        ///   ####.
        /// </summary>
        internal static string level31 {
            get {
                return ResourceManager.GetString("level31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   ########
        ///  #.   $ #
        ///  #.$  # #
        ///  #.# #  #
        ///  ### # ##
        ///   # $  #
        ///   #@ ###
        ///   #####.
        /// </summary>
        internal static string level4 {
            get {
                return ResourceManager.GetString("level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   ########
        ///  #.   $ #
        ///  #.$  # #
        ///  #.# #  #
        ///  ### # ##
        ///   # $  #
        ///   #@ ###
        ///   #####.
        /// </summary>
        internal static string level41 {
            get {
                return ResourceManager.GetString("level41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    ########
        ///  ##..#   #
        ///  # ..# $ ##
        ///  # @ $  $ #
        ///  ##$###   #
        ///   #     ###
        ///   #######.
        /// </summary>
        internal static string level5 {
            get {
                return ResourceManager.GetString("level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    ########
        ///  ##..#   #
        ///  # ..# $ ##
        ///  # @ $  $ #
        ///  ##$###   #
        ///   #     ###
        ///   #######.
        /// </summary>
        internal static string level51 {
            get {
                return ResourceManager.GetString("level51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    #######
        ///   #     ####
        ///   # ###.   #
        ///  ##    # # #
        ///  # .#$ $ # #
        ///  # #  *  # #
        ///  # # $ $#. #
        ///  # # #    ##
        ///  #   .### ##
        ///  ####      #
        ///     #####  #
        ///         #@ #
        ///         ####.
        /// </summary>
        internal static string level6 {
            get {
                return ResourceManager.GetString("level6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    #######
        ///   #     ####
        ///   # ###.   #
        ///  ##    # # #
        ///  # .#$ $ # #
        ///  # #  *  # #
        ///  # # $ $#. #
        ///  # # #    ##
        ///  #   .### ##
        ///  ####      #
        ///     #####  #
        ///         #@ #
        ///         ####.
        /// </summary>
        internal static string level61 {
            get {
                return ResourceManager.GetString("level61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --#########
        ///--#.....  #
        ///--### $ # ##
        ///----# $##  #
        ///----#$ $ $ #
        ///----#   #  #
        ///----##  # @#
        ///-----#######.
        /// </summary>
        internal static string level7 {
            get {
                return ResourceManager.GetString("level7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --#########
        ///--#.....  #
        ///--### $ # ##
        ///----# $##  #
        ///----#$ $ $ #
        ///----#   #  #
        ///----##  # @#
        ///-----#######.
        /// </summary>
        internal static string level71 {
            get {
                return ResourceManager.GetString("level71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       #####
        ///  #####   #
        ///  #.. $ $ ##
        ///  #..$ $  @#
        ///  ##. $## ##
        ///   ###    #
        ///     ######.
        /// </summary>
        internal static string level8 {
            get {
                return ResourceManager.GetString("level8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       #####
        ///  #####   #
        ///  #.. $ $ ##
        ///  #..$ $  @#
        ///  ##. $## ##
        ///   ###    #
        ///     ######.
        /// </summary>
        internal static string level81 {
            get {
                return ResourceManager.GetString("level81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap skin36 {
            get {
                object obj = ResourceManager.GetObject("skin36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wall_Beige {
            get {
                object obj = ResourceManager.GetObject("Wall_Beige", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
